-- Create InspectionProtocols table
CREATE TABLE IF NOT EXISTS "InspectionProtocols" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_InspectionProtocols" PRIMARY KEY AUTOINCREMENT,
    "ProtocolNumber" TEXT NOT NULL,
    "InspectionDate" TEXT NOT NULL,
    "InspectionLocation" TEXT NULL,
    "InspectorName" TEXT NOT NULL,
    "InspectorLicenseNumber" TEXT NULL,
    "ClientId" TEXT NULL,
    "ClientName" TEXT NULL,
    "ClientAddress" TEXT NULL,
    "ClientTaxId" TEXT NULL,
    "CropSprayerSerialNumber" TEXT NULL,
    "CropSprayerName" TEXT NULL,
    "CropSprayerType" TEXT NULL,
    "CropSprayerKind" TEXT NULL,
    "CropSprayerManufacturer" TEXT NULL,
    "CropSprayerProductionYear" TEXT NULL,
    "TankCapacity" TEXT NULL,
    "BoomWidth" TEXT NULL,
    "SectionCount" INTEGER NULL,
    "GeneralConditionPassed" INTEGER NULL,
    "MarkingsReadablePassed" INTEGER NULL,
    "EquipmentCompletePassed" INTEGER NULL,
    "GeneralSectionNotes" TEXT NULL,
    "PumpOperationPassed" INTEGER NULL,
    "PumpSealingPassed" INTEGER NULL,
    "PressurePulsationPassed" INTEGER NULL,
    "PumpSectionNotes" TEXT NULL,
    "AgitatorOperationPassed" INTEGER NULL,
    "AgitatorSectionNotes" TEXT NULL,
    "TankConditionPassed" INTEGER NULL,
    "TankSealingPassed" INTEGER NULL,
    "LevelIndicatorPassed" INTEGER NULL,
    "FlushingSystemPassed" INTEGER NULL,
    "TankSectionNotes" TEXT NULL,
    "ManometerPassed" INTEGER NULL,
    "ManometerReading2Bar" TEXT NULL,
    "ManometerReading4Bar" TEXT NULL,
    "ManometerReading6Bar" TEXT NULL,
    "ManometerDialSizePassed" INTEGER NULL,
    "MeasuringSectionNotes" TEXT NULL,
    "PipesConditionPassed" INTEGER NULL,
    "ConnectionsSealingPassed" INTEGER NULL,
    "PipingSectionNotes" TEXT NULL,
    "SuctionFilterPassed" INTEGER NULL,
    "PressureFilterPassed" INTEGER NULL,
    "NozzleFiltersPassed" INTEGER NULL,
    "FiltrationSectionNotes" TEXT NULL,
    "FieldBoomConditionPassed" INTEGER NULL,
    "BoomStabilityPassed" INTEGER NULL,
    "BoomHeightPassed" INTEGER NULL,
    "BoomSymmetryPassed" INTEGER NULL,
    "OrchardSprayerConditionPassed" INTEGER NULL,
    "AirStreamDirectionPassed" INTEGER NULL,
    "BoomSectionNotes" TEXT NULL,
    "NozzleUniformityPassed" INTEGER NULL,
    "NozzleFlowRatePassed" INTEGER NULL,
    "NozzleConditionPassed" INTEGER NULL,
    "NozzleMeasurements" TEXT NULL,
    "NozzlesSectionNotes" TEXT NULL,
    "TransverseDistributionPassed" INTEGER NULL,
    "CoefficientOfVariation" TEXT NULL,
    "DistributionSectionNotes" TEXT NULL,
    "FinalResult" INTEGER NULL,
    "ValidUntil" TEXT NULL,
    "ControlStickerNumber" TEXT NULL,
    "GeneralNotes" TEXT NULL,
    "CreatedAt" TEXT NOT NULL,
    "UpdatedAt" TEXT NULL,
    "ProtocolXml" TEXT NULL,
    "XslTemplateVersion" TEXT NULL,
    "XmlGeneratedAt" TEXT NULL
);

-- Create migrations history table if it doesn't exist
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

-- Mark all migrations as applied
INSERT OR IGNORE INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES 
    ('20260108133554_InitialCreate', '10.0.1'),
    ('20260116083432_AddOwnerIdToMachine', '10.0.1'),
    ('20260116122825_AddClientTable', '10.0.1'),
    ('20260206200844_AddInspectionProtocolsTable', '10.0.1');
